services:
  web:
    image: "${project_name}:${ruby_version}"
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: ${project_name}
        RUBY_VERSION: ${ruby_version}
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
